name: Update Sync File

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v3

      - name: Sync File to Target Repository
        env:
          TARGET_PAT: ${{ secrets.SYNC_PAT }}
        run: |
          # Set konfigurasi Git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Clone repository tujuan
          git clone https://x-access-token:${TARGET_PAT}@github.com/aplsmalab-svg/4535m3n.git target_repo

          # Salin file html dari repo lokal ke repo tujuan
          cp qscdrtkju34okvbfdehmksbgtsbhushjwon12.html target_repo/qscdrtkju34okvbfdehmksbgtsbhushjwon12.html

          # Masuk ke direktori repo tujuan & commit
          cd target_repo
          git add qscdrtkju34okvbfdehmksbgtsbhushjwon12.html
          
          # Kirim perubahan jika terdapat pembaruan file
          if ! git diff-index --quiet HEAD; then
            git commit -m "Auto-sync updated HTML from source repository"
            git push origin main
          else
            echo "Tidak ada perubahan file untuk disinkronkan."
          fi
